### ISSUE TITLE
Potential error message improvement on failure? 

### ISSUE THREAD

**Issue by Quafadas** [disneystreaming/smithy-translate#23]
If one creates an open-api spec, which would create a smithy model, which would fail due to https://github.com/awslabs/smithy/issues/1029

then you'll get something along these lines;
``` 
        at software.amazon.smithy.model.validation.ValidatedResult.validate(ValidatedResult.java:145)
        at software.amazon.smithy.model.validation.ValidatedResult.unwrap(ValidatedResult.java:132)
        at smithytranslate.openapi.OpenApiCompiler$.validate(OpenApiCompiler.scala:150)
        at smithytranslate.openapi.OpenApiCompiler$.$anonfun$compile$5(OpenApiCompiler.scala:140)
        at scala.util.Try$.apply(Try.scala:210)
        at smithytranslate.openapi.OpenApiCompiler$.compile(OpenApiCompiler.scala:140)
        at smithytranslate.openapi.OpenApiCompiler$.parseAndCompile(OpenApiCompiler.scala:125)
        at smithytranslate.cli.runners.openapi.ParseAndCompile$.openapi(ParseAndCompile.scala:40)
        at smithytranslate.cli.runners.OpenApi$.runOpenApi(OpenApi.scala:35)
        at smithytranslate.cli.Main$$anonfun$$lessinit$greater$1.apply(Main.scala:34)
        at smithytranslate.cli.Main$$anonfun$$lessinit$greater$1.apply(Main.scala:32)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
        at cats.data.Validated.andThen(Validated.scala:727)
        at com.monovore.decline.Result.$anonfun$mapValidated$2(Result.scala:13)
        at cats.instances.Function0Instances$$anon$4.$anonfun$map$1(function.scala:96)
        at com.monovore.decline.Parser.evalResult(Parser.scala:30)
        at com.monovore.decline.Parser.$anonfun$consumeAll$3(Parser.scala:107)
        at scala.util.Either.flatMap(Either.scala:352)
        at com.monovore.decline.Parser.$anonfun$consumeAll$1(Parser.scala:107)
        at scala.Option.map(Option.scala:242)
        at com.monovore.decline.Parser.consumeAll(Parser.scala:106)
        at com.monovore.decline.Parser.apply(Parser.scala:19)
        at com.monovore.decline.Command.parse(opts.scala:20)
        at smithytranslate.cli.CommandApp.main(CommandApp.scala:81)
        at smithytranslate.cli.Main.main(Main.scala)
```
But right at the bottom of the console output. 

For a larger spec, it can be hard relatively difficult to discern that the error takes place a long way further up the logs, because those errors tend to drown in the warnings - they may even be lost in console truncation. 

After minimizing, I think the important part was this...  

```
Failed to validate the produced Smithy model. The following is a list of
error messages followed by the validation exception from Smithy:

software.amazon.smithy.model.validation.ValidatedResultException: Result contained ERROR severity validation events: 
``` 
But it was relatively difficult, to spot.

Depending on the effort required, I wonder if it's possible to bubble the smithy errors to the _bottom_ of the log, or somehow ignore all the warnings in this situation in an attempt to get the errors front and center?

**Comment by Quafadas** [comment]
Yes - I’ll do this but need to minimise - bear with me

**Comment by Quafadas** [comment]
The below spec would be such an example. If you remove either of the two endpoints, it'll produce valid smithy (or at least it runs through).  

As is, it'll crash with the above

```
{
    "openapi": "3.0.1",
    "info": {
        "title": "Testers Service v1",
        "description": "",
        "contact": {
            "name": "",
            "url": ""
        },
        "version": "1.0"
    },
    "servers": [
        {
            "url": ""
        }
    ],
    "paths": {
        "/Testers/{id}": {
            "get": {
                "tags": [
                    "Testers"
                ],
                "summary": "Testers_GetTest",
                "operationId": "Testers_GetTest",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Format - uuid.",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "format": "uuid"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "text/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Testers.DataContracts.Responses.Command.GetTestByIdCommandResponse"
                                },
                                "example": {
                                    "Test": {
                                        
                                    }
                                }
                            }
                        }
                    }
                }            
            }
        },
        "/Testers/queries/unique-tags": {
            "get": {
                "tags": [
                    "Testers"
                ],
                "summary": "Testers_GetTestTags",
                "operationId": "Testers_GetTestTags",
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "text/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Testers.DataContracts.Responses.Command.GetUniqueTestTagsCommandResponse"
                                },
                                "example": {
                                    "tags": [
                                        "string"
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Testers.DataContracts.Responses.Command.GetUniqueTestTagsCommandResponse": {
                "type": "object",
                "properties": {
                    "tags": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "nullable": true
                    }
                },
                "additionalProperties": false
            },            
            "Testers.DataContracts.Responses.Command.GetTestByIdCommandResponse": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string",
                        "format": "uuid"
                    }
                },
                "additionalProperties": false
            }
        }
    }
}``

**Comment by daddykotex** [comment]
I'll close this issue as I think #25 greatly improve the situation: it reports only ERROR/DANGER validation error as well as the stack. You can retrieve the previous behaviour by using the debug flag.
